;/*FB_PKG_DELIM*/

__d("KadabraQPImagineVideoEducationalTipStartTrigger.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e="imagine_video_educational_tip_start",l={get:function(){return e}};i.default=l}),66);
__d("KadabraQPImagineVideoFreeGenerationsStartTrigger.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e="imagine_video_free_generations_start",l={get:function(){return e}};i.default=l}),66);
__d("KadabraQPImagineVideoPlayerAutoTrimmedTrigger.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e="imagine_video_player_auto_trimmed",l={get:function(){return e}};i.default=l}),66);
__d("KadabraUnifiedCanvasRootQuery_abraRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26634505666140143"}),null);
__d("kadabra_media_concord_voice_over.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("1314")}};l.default=e}),98);
__d("kadabra_mweb_imagine_simplification.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("6835")}};l.default=e}),98);
__d("KadabraUnifiedCanvasRootQuery$Parameters",["AbraSurfaceNuxID.relayprovider","KadabraQPImagineVideoEducationalTipStartTrigger.relayprovider","KadabraQPImagineVideoFreeGenerationsStartTrigger.relayprovider","KadabraQPImagineVideoPlayerAutoTrimmedTrigger.relayprovider","KadabraUnifiedCanvasRootQuery_abraRelayOperation","WebPixelRatio.relayprovider","enable_kadabra_partial_results.relayprovider","enable_swap_me_on_kadabra.relayprovider","kadabra_imagine_canvas_enable_dev_settings.relayprovider","kadabra_media_concord_voice_over.relayprovider","kadabra_mweb_imagine_simplification.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("KadabraUnifiedCanvasRootQuery_abraRelayOperation"),metadata:{},name:"KadabraUnifiedCanvasRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__kadabra_mweb_imagine_simplificationrelayprovider:n("kadabra_mweb_imagine_simplification.relayprovider"),__relay_internal__pv__kadabra_imagine_canvas_enable_dev_settingsrelayprovider:n("kadabra_imagine_canvas_enable_dev_settings.relayprovider"),__relay_internal__pv__enable_kadabra_partial_resultsrelayprovider:n("enable_kadabra_partial_results.relayprovider"),__relay_internal__pv__kadabra_media_concord_voice_overrelayprovider:n("kadabra_media_concord_voice_over.relayprovider"),__relay_internal__pv__AbraSurfaceNuxIDrelayprovider:n("AbraSurfaceNuxID.relayprovider"),__relay_internal__pv__KadabraQPImagineVideoEducationalTipStartTriggerrelayprovider:n("KadabraQPImagineVideoEducationalTipStartTrigger.relayprovider"),__relay_internal__pv__KadabraQPImagineVideoFreeGenerationsStartTriggerrelayprovider:n("KadabraQPImagineVideoFreeGenerationsStartTrigger.relayprovider"),__relay_internal__pv__KadabraQPImagineVideoPlayerAutoTrimmedTriggerrelayprovider:n("KadabraQPImagineVideoPlayerAutoTrimmedTrigger.relayprovider"),__relay_internal__pv__enable_swap_me_on_kadabrarelayprovider:n("enable_swap_me_on_kadabra.relayprovider"),__relay_internal__pv__WebPixelRatiorelayprovider:n("WebPixelRatio.relayprovider")}}};a.exports=e}),null);
__d("KadabraUnifiedCanvasRootRemixQuery_abraRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25172274275765106"}),null);
__d("KadabraUnifiedCanvasRootRemixQuery$Parameters",["KadabraUnifiedCanvasRootRemixQuery_abraRelayOperation","enable_kadabra_partial_results.relayprovider","kadabra_imagine_canvas_enable_dev_settings.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("KadabraUnifiedCanvasRootRemixQuery_abraRelayOperation"),metadata:{},name:"KadabraUnifiedCanvasRootRemixQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__kadabra_imagine_canvas_enable_dev_settingsrelayprovider:n("kadabra_imagine_canvas_enable_dev_settings.relayprovider"),__relay_internal__pv__enable_kadabra_partial_resultsrelayprovider:n("enable_kadabra_partial_results.relayprovider")}}};a.exports=e}),null);
__d("KadabraUnifiedCanvasRoot.entrypoint",["JSResourceForInteraction","KadabraUnifiedCanvasFilmStrip.entrypoint","KadabraUnifiedCanvasRootQuery$Parameters","KadabraUnifiedCanvasRootRemixQuery$Parameters","NestedRelayEntryPointBuilderUtils","buildKadabraRoute.entrypoint","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=r("JSResourceForInteraction")("KadabraUnifiedCanvasRoot.react").__setRef("KadabraUnifiedCanvasRoot.entrypoint"),s=r("buildKadabraRoute.entrypoint")(e,function(e){var t,n=e.passthroughProps,a=e.routeParams,i=n!=null?n:{},l=i.initial_media_id,s=a.media_id,u=a.prompt_id,c=a.remix,d=c===void 0?!1:c,m=a.remix_video_id,p=r("gkx")("3911")?d:!1,_=p&&m==null?void 0:o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:r("KadabraUnifiedCanvasFilmStrip.entrypoint"),entryPointParams:{media_id:l!=null?l:s,prompt_id:u,requested_media_type:m!=null?"IMAGES":void 0}});return{entryPoints:babelHelpers.extends({},_?{filmstripEntrypoint:_}:{}),queries:{queryRef:{parameters:r("KadabraUnifiedCanvasRootQuery$Parameters"),variables:{media_id:s!=null?s:"",media_id_is_null:s==null,prompt_id:u!=null?u:"",prompt_id_is_null:u==null,remix:p}},remixQueryRef:{parameters:r("KadabraUnifiedCanvasRootRemixQuery$Parameters"),variables:{remix_video_id:m!=null?m:"",remix_video_id_is_null:m==null,source_override_id:(t=a.source_override_id)!=null?t:"",source_override_id_is_null:a.source_override_id==null}}}}});l.default=s}),98);