;/*FB_PKG_DELIM*/

__d("KadabraNewPromptHeaderRoot.entrypoint",["JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.isVoiceOpen;return{extraProps:{isVoiceOpen:e},queries:{}}},root:r("JSResourceForInteraction")("KadabraNewPromptHeaderRoot.react").__setRef("KadabraNewPromptHeaderRoot.entrypoint")};l.default=e}),98);
__d("KadabraNewPromptRootPromptIcebreakerQuery_abraRelayOperation",[],(function(t,n,r,o,a,i){a.exports="30320195984230807"}),null);
__d("KadabraNewPromptRootPromptIcebreakerQuery$Parameters",["KadabraNewPromptRootPromptIcebreakerQuery_abraRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("KadabraNewPromptRootPromptIcebreakerQuery_abraRelayOperation"),metadata:{},name:"KadabraNewPromptRootPromptIcebreakerQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("KadabraNewPromptRootQuery_abraRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24377900841886785"}),null);
__d("KadabraNewPromptRootQuery$Parameters",["AbraQPDocUploadNuxTriggerName.relayprovider","AbraSurfaceNuxID.relayprovider","KadabraNewPromptRootQuery_abraRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("KadabraNewPromptRootQuery_abraRelayOperation"),metadata:{},name:"KadabraNewPromptRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__AbraQPDocUploadNuxTriggerNamerelayprovider:n("AbraQPDocUploadNuxTriggerName.relayprovider"),__relay_internal__pv__AbraSurfaceNuxIDrelayprovider:n("AbraSurfaceNuxID.relayprovider")}}};a.exports=e}),null);
__d("KadabraNewPromptRoot.entrypoint",["JSResourceForInteraction","KadabraNewPromptHeaderRoot.entrypoint","KadabraNewPromptRootPromptIcebreakerQuery$Parameters","KadabraNewPromptRootQuery$Parameters","NestedRelayEntryPointBuilderUtils","buildKadabraRoute.entrypoint","cr:16034"],(function(t,n,r,o,a,i,l){"use strict";var e=r("JSResourceForInteraction")("KadabraNewPromptRoot.react").__setRef("KadabraNewPromptRoot.entrypoint"),s=r("buildKadabraRoute.entrypoint")(e,function(e){var t,a,i,l=n("cr:16034")!=null?o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:n("cr:16034"),entryPointParams:{}}):void 0,s=l!=null&&e.routeParams.voice===!0,u=o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:r("KadabraNewPromptHeaderRoot.entrypoint"),entryPointParams:{isVoiceOpen:s}}),c=(t=e.routeParams)==null?void 0:t.icebreaker_id;return{entryPoints:{headerEntrypoint:u,newVoicePromptEntrypoint:l},extraProps:babelHelpers.extends({collapseNav:s,fullscreen:!0},c!=null?{icebreakerId:c}:{},{icebreakerType:(a=e.passthroughProps)==null?void 0:a.icebreakerType,metaAIEntryPoint:(i=e.passthroughProps)==null?void 0:i.metaAIEntryPoint}),queries:babelHelpers.extends({},c!=null?{promptIcebreakerQueryRef:{parameters:r("KadabraNewPromptRootPromptIcebreakerQuery$Parameters"),variables:{encoded_convo_starter_id:c}}}:{},{promptQueryRef:{parameters:r("KadabraNewPromptRootQuery$Parameters"),variables:{}}})}});l.default=s}),98);
__d("KadabraNewVoicePromptRootQuery_abraRelayOperation",[],(function(t,n,r,o,a,i){a.exports="10010674415679776"}),null);
__d("KadabraNewVoicePromptRootQuery$Parameters",["KadabraNewVoicePromptRootQuery_abraRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("KadabraNewVoicePromptRootQuery_abraRelayOperation"),metadata:{},name:"KadabraNewVoicePromptRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("KadabraNewVoicePromptRoot.entrypoint",["JSResourceForInteraction","KadabraNewVoicePromptRootQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{queryRef:{parameters:r("KadabraNewVoicePromptRootQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("KadabraNewVoicePromptRoot.react").__setRef("KadabraNewVoicePromptRoot.entrypoint")};l.default=e}),98);